# Generated by Django 3.2.8 on 2021-10-15 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='employee',
            field=models.ManyToManyField(related_name='company', to='CompanyApp.Employees'),
        ),
    ]
