# Generated by Django 3.2.8 on 2021-10-15 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApp', '0002_alter_company_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CompanyApp.company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='employee',
            field=models.ManyToManyField(related_name='employee', to='CompanyApp.Employees'),
        ),
    ]
